apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff
spec:
  replicas: 1
  selector:
    matchLabels:
        app: timeoff
  template:
    metadata:
      labels:
        app: timeoff
    spec:
      containers:
        - name: timeoff
          image: fabianrp7/timeoff:1.0.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: timeoff
spec:
  ports:
  - nodePort: 32330
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: timeoff
  sessionAffinity: None
  type: NodePort
